### ISSUE TITLE
受付開始待ちのレポートと、完了したレポートが同じ扱いになっている問題

### ISSUE THREAD

**Issue by Cider006** [twin-te/manaba-report-integration#2]
- **内容**
レポートが受付開始待ち(受付開始日時より前に公開されているレポート)の状態の場合、提出できないにも関わらず提出したレポートと同じ扱いになっている。
- **要望**
受付開始待ちのレポートも未提出の課題と同様に扱うようにしてほしい。

**Comment by SIY1121** [comment]
修正しました
