### ISSUE TITLE
正常にサービスが登録できない

### ISSUE THREAD

**Issue by onokatio** [twin-te/manaba-report-integration#23]
# 環境

ブラウザ: Google Chrome
拡張機能: 最新版

# 症状・再現方法

インストール後、拡張機能のポップアップからTrelloやGoogle Taskを選択し、新しいウィンドウから当該サービスにログインすると、数回に一回登録が完了せず何も起こらない。

# 検証

コードをいじって検証してみましたが、Google Chromeの拡張機能のポップアップ内で`chrome.identity.launchWebAuthFlow`を呼び出し、その状態でポップアップが何らかの原因で消える（フォーカスが外れるなど）とそのコールバックが呼ばれないようです。
実際、このコールバック部分に適当な処理（console.logなど）を書いても、ポップアップが外れると新規ウィンドウは残っていても動作しないことがわかりました。おそらくどこかで非同期処理が廃棄されるのではないかと思われます。

該当部分:
https://github.com/twin-te/manaba-report-integration/blob/247a369fcdc5aed4add2d55e59be4b5c900d6000/src/repositories/trello.ts#L21-L37

# 修正方法

ポップアップ(`popup.html`)内ではなく、設定ページ（manifest.jsonの`options_ui`or`options_page`）や適当な新しいタブ内でサービスの登録を行えば解決できると思います。

**Comment by onokatio** [comment]
# 追記

問題が頻出する環境としては、

- ブラウザ: Chrome
- OS: Linux
  - 特にマウスを移動するだけでフォーカスが外れるタイプのウィンドウマネージャを利用している場合

や

- ブラウザ: Firefox(#17)
- OS: MacOS

などです。

**Comment by HosokawaR** [comment]
バグを報告いただきありがとうございます！
反応が遅れすみません。

こちらでも同様のバグを認知しました。原因は書いてくださった通り、拡張機能の Popup は開くたびに状態がリセットされるため、Popup が一度閉じられると `launchWebAuthFlow` の Callback が実行されないためだと推測されます。

現状は提案していただいた設定ページでサービスの登録を行う方法を検討しております。

**Comment by onokatio** [comment]
@HosokawaR この件何か進んでたりしますか？
まだ手をつけていないのであれば自分がPR出してもいいでしょうか。

**Comment by HosokawaR** [comment]
> @HosokawaR この件何か進んでたりしますか？ 

まだ進展はありません。

> まだ手をつけていないのであれば自分がPR出してもいいでしょうか。

はい！PR はいつでも歓迎です。
ありがとうございます！

設定を Popup ではなく別タブなどで行う場合、デザインを変更しなくては行けない場合があると思います。
もしデザインの方針がよくわからなければ、機能を実装した PR だけ出していただき、後からこちらでデザインを整えることもできます。あるいはデザインの方針について質問いただいても幸いです。

**Comment by onokatio** [comment]
了解いたしました！ひとまずコンポーネントいじらずに設定に移動するだけのPR出してみます。
