### ISSUE TITLE
`log` レベルのデバッグ情報がコンソールに表示される

### ISSUE THREAD

**Issue by yudukikun5120** [twin-te/manaba-report-integration#24]
こんばんは。
本サービスを利用させて頂いている者です。

大変便利な製品で，開発者の方々に感謝申し上げます。

さて，現状は以下の画像に示す通りコンソール上にデバッグ情報が出力されていますが，これは仕様でしょうか。
<img width="797" alt="スクリーンショット 2022-10-30 22 36 50" src="https://user-images.githubusercontent.com/45707929/198881491-1f10a1a6-38fb-4656-904f-43b47bcdc2ac.png">

ご確認願えれば幸いです。

**Comment by HosokawaR** [comment]
@SIY1121 
（気づいていいなさそうなので一応メンションをします

**Comment by SIY1121** [comment]
デバッグ時の消し忘れですね
一般利用で目にすることは無いと思うので、別の機能をリリースするタイミングがあれば一緒に削除しておきます
