### ISSUE TITLE
GitHub Project (beta) を export 先に追加する

### ISSUE THREAD

**Issue by azrsh** [twin-te/manaba-report-integration#25]
- GitHub の Issue を自動で作成し、GitHub Project (beta) に追加する
- GitHub Project (beta) のカラムに `Due` を追加して〆切を書き込む

**Comment by azrsh** [comment]
@SIY1121 この内容で PR を出したいのですが、実装したらこのリポジトリに取り込んでもらうことはできますか？
それと Trello や Google Tasks はクライアントライブラリを使用せずに実装されていますが、この issue の場合もそうしなければいけないでしょうか？

**Comment by SIY1121** [comment]
@azarashi2931 取り込むことは可能です 👍 
依存するライブラリが少ないに越したことはありませんが、任意のクライアントライブラリを使っていただいても構いません。

**Comment by azrsh** [comment]
了解です。ありがとうございます！
