### ISSUE TITLE
Node.js のバージョンを固定する

### ISSUE THREAD

**Issue by azrsh** [twin-te/manaba-report-integration#35]
- 開発用の Node.js のバージョンを nodeenv や volta の類で固定したい

**Comment by HosokawaR** [comment]
わかるよ

**Comment by azrsh** [comment]
多分今は 16 台なら動く状態

**Comment by HosokawaR** [comment]
Node の engines と、volta や nodeenv の類の指定どっちがいいんだろう？
両方？

**Comment by azrsh** [comment]
engines はパッケージが動作する Node.js のバージョンを表明するもので、今回は開発のための Node.js のバージョンの話なので engines はどうなん？って感じ

**Comment by azrsh** [comment]
あんまり詳しくない

**Comment by azrsh** [comment]
> engines はパッケージが動作する Node.js のバージョンを表明するもので、今回は開発のための Node.js のバージョンの話なので engines はどうなん？って感じ

裏で聞いてみたところ概ねこの認識であってそう

**Comment by azrsh** [comment]
こだわりがなければ Volta で固定するけどどうですか？

**Comment by HosokawaR** [comment]
https://github.com/volta-cli/volta/issues/742#issuecomment-631588143

> engines はパッケージが動作する Node.js のバージョンを表明するもので、今回は開発のための Node.js のバージョンの話なので engines はどうなん？って感じ

Volta 的にもそういう使い分けらしいのでそれがいいと思いました。

Volta で異論なしです

**Comment by azrsh** [comment]
あい、ではそのような PR を出します

**Comment by takonasu** [comment]
参考程度ですが，他のTwin:teリポジトリではnvmを使っているものもあります
https://github.com/twin-te/twinte-sponsorship
(nodeバージョンの管理ツールは特にTwin:teとしては統一していないです）
