### ISSUE TITLE
graphql-requestとgraphql-tagへの依存が書かれていない

### ISSUE THREAD

**Issue by onokatio** [twin-te/manaba-report-integration#64]
codegenによって生成されたgithub用のソースコードは、[graphql-request](https://github.com/prisma-labs/graphql-request)パッケージと[graphql-tag](https://github.com/apollographql/graphql-tag)パッケージに依存しているため`dependencies`に追記する必要があるが書かれていない。

`devDependencies`に書いてある`@graphql-codegen/typescript-graphql-request`プラグインが内部的に依存しているため現在は`npm install`すると`node_modules`以下に一緒くたに入って実行できてしまうが、本来であればやはり`dependencies`に書くべきかと思われます。

```
$ npm ls graphql-request
manaba-report-integration@1.2.0 /Users/katio/script/github.com/onokatio/manaba-report-integration
├─┬ @graphql-codegen/cli@2.13.12
│ └─┬ @graphql-tools/prisma-loader@7.2.42
│   └── graphql-request@5.0.0 deduped
└─┬ @graphql-codegen/typescript-graphql-request@4.5.8
  └── graphql-request@5.0.0
```

**Comment by onokatio** [comment]
なんか気になったため厄介オタクみたいなIssueを出してしまったが、現状動作に問題はないためどうしても修正しないといけないという理由はないと思います。
ちなみに気づいた原因としては、yarnではなくpnpm (node_modulesを分離する型のパッケージマネージャ) でビルドを試した時に転けたからです。

**Comment by onokatio** [comment]
PR出すだけだしたので気が向いた時にでも。

**Comment by HosokawaR** [comment]
ありがとうございます！

いえいえ、いつも PR を出していただいてとても感謝しております。

申し訳ないのですが、最近は期末テスト期間により、いただいた PR をすぐに見ることができない状況です。
期末テストが終わり次第、なるはやで見させていただきます！

おまたせしてすみません。

**Comment by onokatio** [comment]
@HosokawaR 丁寧にありがとうございます！
お忙しい時に恐縮です。PR対応はいつでも構わないので、定期試験頑張ってください。
